### ISSUE TITLE
Provide an example on how to compose two images together

### ISSUE THREAD

**Issue by dimsuz** [RaphaelJ/friday-examples#1]
Would it be possible to provide some example which would show how to put one image on top of another?

For example I have two RGBA images with transparency. And I'd like to do DST_ATOP (in porterduff terminology) - how to do this?

Initially I thought that I might be able to do something like `zipWith f img1 img2`, but there's no `zip` in friday, only `map`.

Any advice?

**Comment by TomMD** [comment]
Just make a new image:

```
-- Assuming shape a == shape b
zipWith f a b = fromFunction (shape a) (\idx -> f (a ! idx) (b ! idx))
```

**Comment by dimsuz** [comment]
Neat! Thank you, will try this!
(I'm a beginner both at haskell image processing and friday)
